In [1]:
import pandas as pd

In [3]:
titanic = pd.read_excel('titanic3.xls', index_col='name')
titanic

,pclass,survived,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
name,,,,,,,,,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
"Allison, Master. Hudson Trevor",1,1,male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
"Allison, Miss. Helen Loraine",1,0,female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Zabour, Miss. Hileni",3,0,female,14.5000,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
"Zabour, Miss. Thamine",3,0,female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
"Zakarian, Mr. Mapriededer",3,0,male,26.5000,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
"Zakarian, Mr. Ortin",3,0,male,27.0000,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
"Zimmerman, Mr. Leo",3,0,male,29.0000,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [10]:
titanic.sort_index(inplace=True)
titanic.head(5)

,pclass,survived,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
name,,,,,,,,,,,,,
"Abbing, Mr. Anthony",3,0,male,42.0,0,0,C.A. 5547,7.55,NaN,S,NaN,NaN,NaN
"Abbott, Master. Eugene Joseph",3,0,male,13.0,0,2,C.A. 2673,20.25,NaN,S,NaN,NaN,"East Providence, RI"
"Abbott, Mr. Rossmore Edward",3,0,male,16.0,1,1,C.A. 2673,20.25,NaN,S,NaN,190.0,"East Providence, RI"
"Abbott, Mrs. Stanton (Rosa Hunt)",3,1,female,35.0,1,1,C.A. 2673,20.25,NaN,S,A,NaN,"East Providence, RI"
"Abelseth, Miss. Karen Marie",3,1,female,16.0,0,0,348125,7.65,NaN,S,16,NaN,"Norway Los Angeles, CA"

In [12]:
titanic.loc['Abbott, Master. Eugene Joseph', ['fare', 'sex']]

fare    20.25
sex      male
Name: Abbott, Master. Eugene Joseph, dtype: object